### PR TITLE
Solo 12 new project not clearing old project

### PR DESCRIPTION
**Pull request by MatzElectronics**
Two changes:
 - The UI warning linking to the client downloads was being disabled, but by using jQuery, it won't throw an error if it can't find it.  The ID for the link will need to be restored in the Solo and BlocklyProp blocklyc.html/jsp pages
 - The new project modal is now using the title ("New Project" vs. "Edit Project Details" to determine whether the project code currently in the editor should be cleared.

To test:
 - Open a project or start a new project and add code.
 - Click the "new project" link the top-left dropdown.
 - Fill in the info for a new project
 - Click "continue", toolbox and canvas should be clear and set correctly for the specified board
 - save, reopen, ensure project only contains new code and name/board type persisted.

### CODE REVIEW

**Comment by PropGit** [comment]
Regarding the UI Warning - is this what I have been affected by in Production recently?  If BP Launcher is closed, the yellow warning appears in the browser, but a relaunch of the BP Launcher doesn't cause it to reconnect... a refresh doesn't work either.  I don't recall that happening before.  I don't see errors in the console.  The only workaround is for me to close, refresh/reload the BP Launcher app in Chrome, then relaunch it.

**Comment by MatzElectronics** [comment]
Possibly...It's hard to say without seeing the an error, and even harder
when no error is produced.

**Comment by MatzElectronics** [comment]
Yes - you'll need the most current index.html and blocklyc.html in
solo/develop in order for this to work.

**Comment by pjewald** [comment]
Ok, let's add a reference to the PR on the Solo repo that is required for this update.

I retested with the develop branch on Solo and the this PR in the CDN repo. After clicking on the 'Continue' button, the editor canvas appears to clear momentarily and then the last project I created, but not saved, reappears on the editor canvas. 

I can verify that the project that appears on the editor canvas is also stored in window.LocalStorage.localProject. I am going to postulate that something is loading that project after the code that is supposed to clear the currentProject object.

**Comment by pjewald** [comment]
It seems that browsers are especially stingy in releasing cached data. The update works as specified once all of the dependencies are updated.

**Comment by pjewald** [comment]
This fixes issue parallaxinc/solo#12.

**Pull request merged**
